# Generated by Django 5.0.4 on 2024-04-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('total_rooms', models.IntegerField()),
                ('nightly_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
