# Generated by Django 5.0.4 on 2024-04-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('total_rooms', models.IntegerField()),
                ('nightly_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
