# Generated by Django 5.0.4 on 2024-04-23 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_invoice_invoice_id_invoice_id_and_more'),
        ('userprofile', '0002_userprofile_city_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.AddField(
            model_name='invoice',
            name='userprofile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile'),
            preserve_default=False,
        ),
    ]
