# Generated by Django 5.0.4 on 2024-04-27 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_alter_flight_airline'),
        ('hotel', '0002_remove_hotel_hotel_id_hotel_id'),
        ('review', '0003_remove_review_booking_id_review_booking'),
        ('tour', '0002_tour_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
        migrations.AddField(
            model_name='review',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.flight'),
        ),
        migrations.AddField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.tour'),
        ),
    ]
