# Generated by Django 5.0.4 on 2024-04-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('airline', models.CharField(max_length=10)),
                ('flight_date', models.DateField()),
                ('flight_time', models.TimeField()),
                ('departure_city', models.CharField(max_length=20)),
                ('arrival_city', models.CharField(max_length=20)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_seats', models.IntegerField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
