# Generated by Django 5.0.4 on 2024-04-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_remove_flight_flight_id_flight_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='booked_seats',
            field=models.IntegerField(default=0),
        ),
    ]
