# Generated by Django 5.0.4 on 2024-04-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_flight_booked_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(max_length=50),
        ),
    ]
