# Generated by Django 5.0.4 on 2024-04-29 17:20

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0001_initial'),
        ('hotel', '0001_initial'),
        ('tour', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 4, 29))])),
                ('reservation_end_date', models.DateField()),
                ('num_of_guests', models.IntegerField()),
                ('traveler_fname', models.CharField(max_length=20)),
                ('traveler_lname', models.CharField(max_length=20)),
                ('booking_date', models.DateField()),
                ('status', models.CharField(choices=[('payment pending', 'Payment Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status_change_date', models.DateField(blank=True, null=True)),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flight.flight')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.hotel')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.tour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
