# Generated by Django 5.0.4 on 2024-04-23 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0002_remove_flight_flight_id_flight_id'),
        ('hotel', '0002_remove_hotel_hotel_id_hotel_id'),
        ('tour', '0001_initial'),
        ('userprofile', '0002_userprofile_city_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('reservation_end_date', models.DateField()),
                ('num_of_guests', models.IntegerField()),
                ('traveler_fname', models.CharField(max_length=20)),
                ('traveler_lname', models.CharField(max_length=20)),
                ('booking_date', models.DateField()),
                ('status', models.CharField(choices=[('payment pending', 'Payment Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=20)),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flight.flight')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.hotel')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.tour')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile')),
            ],
        ),
    ]
